#!/usr/bin/env python3

import argparse
from mdlint import Report
from libmdlint import Main

if __name__ == '__main__':
    
    parser = argparse.ArgumentParser()
    
    parser.add_argument('-v', '--verbose', action='store_true')
    parser.add_argument('-u', '--update', action='store_true')
    
    parser.add_argument('-o', '--output')
    parser.add_argument('source')

    args = parser.parse_args()

    docs_report = Main(args)
